#!/usr/bin/env ruby
# frozen_string_literal: true

require 'abstract_command'

module Command
  # Template for Git 'diff-index' command
  class GitDiffIndex < AbstractCommand
    def template
      'git diff-index --name-only --diff-filter=ACMR HEAD'
    end
  end
  # Template for 'bleacher' command
  class Bleacher < AbstractCommand
    def template
      'bleacher -f %<filename>s'
    end
  end
end

Command::GitDiffIndex.new.backtick.each_line.map do |file|
  unless Command::Bleacher.new(filename: file.chomp).system
    warn 'Aborting commit operation.'
    exit 1
  end
end
