#!/usr/bin/env ruby
# frozen_string_literal: true

require 'abstract_command'

module Command
  # Template for Git 'diff-index' command
  class GitDiffIndex < AbstractCommand
    def template
      'git diff-index --name-only --diff-filter=ACMR HEAD'
    end
  end
  # Template for 'bleach' command
  class Bleach < AbstractCommand
    def template
      'bleach -f %<filename>s'
    end
  end
end

Command::GitDiffIndex.new.backtick.each_line.map do |file|
  exit 1 unless Command::Bleach.new(filename: file.chomp).system
end
