AllCops:
  TargetRubyVersion: 2.7
  DisabledByDefault: true
  Include:
    - '**/*.rb'
    - '**/*.arb'
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.rbuild'
    - '**/*.rbw'
    - '**/*.rbx'
    - '**/*.ru'
    - '**/*.ruby'
    - '**/Gemfile'
    - '**/Rakefile'

Layout/AlignHash:
  Enabled: true
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: ignore_implicit
Layout/IndentationWidth:
  Enabled: true
Layout/IndentationConsistency:
  Enabled: true
Layout/SpaceAfterColon:
  Enabled: true
Layout/RescueEnsureAlignment:
  Enabled: true
Layout/InitialIndentation:
  Enabled: true
Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf
Layout/TrailingWhitespace:
  Enabled: true
Layout/SpaceAroundOperators:
  Enabled: true
Layout/SpaceInsideBlockBraces:
  Enabled: true
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
Layout/SpaceInsideParens:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true
Layout/Tab:
  Enabled: true
Lint/Debugger:
  Enabled: true
Lint/RescueException:
  Enabled: true

Style/StringLiterals:
  Enabled: true



